config/routes.rb
Rails.application.routes.draw do
  root 'world#index'
  get '/click_check' => 'world#click_check'
  post '/world/:world_id/highscore' => 'highscore#create', as: 'world_highscores'
  resources :world, only: [:show, :index] do 
    resources :highscore, only: [:new, :create, :index]
  end
  

 

end

app/models/highscore.rb
class Highscore < ActiveRecord::Base
  belongs_to :world
  validates :world_id, :name, :time, presence: true

end

app/models/hitbox.rb
class Hitbox < ActiveRecord::Base
  belongs_to :world
  validates :world_id, :character, :x_left, :x_right, :y_top, :y_bottom, presence: true
  validates_inclusion_of :character, in: %w( Waldo Odlaw Whitebeard Wenda )
end

app/models/world.rb
class World < ActiveRecord::Base
  has_attached_file :image, styles: { thumb: "300x200" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  has_many :hitboxes, dependent: :destroy
  has_many :highscores, dependent: :destroy

  def get_hidden_characters
    characters = []
    self.hitboxes.each do |h|
      characters << h.character
    end
    return characters
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/highscore_controller.rb
class HighscoreController < ApplicationController

  def new
    @world = World.find(params[:world_id])
    @highscore = @world.highscores.new
  end

  def index
    @world = World.find(params[:world_id])
    @highscores = Highscore.where(world_id: params[:world_id]).order(:time).limit(20)
  end

  def create
    @world = World.find(params[:world_id])
    @highscore = @world.highscores.new(highscore_params)
    if @highscore.save
      redirect_to world_highscore_index_path(world: highscore_params[:world_id]) # need to somehow get the world in there
    else
      render 'new'
    end
  end

  private

  def highscore_params
    params.require(:highscore).permit(:name, :time, :world_id)
  end

end

app/controllers/world_controller.rb
class WorldController < ApplicationController
  before_action :set_world, only: [:show, :click_check]

  def show
    @characters = @world.get_hidden_characters
  end

  def index
    @worlds = World.all
  end

  def click_check
    x_coord = params[:x_coord].to_f
    y_coord = params[:y_coord].to_f
    character = params[:character]
    hitbox = @world.hitboxes.find_by_character(character)
    hit_status = ((x_coord >= hitbox.x_left) && (x_coord <= hitbox.x_right) && (y_coord >= hitbox.y_top) && (y_coord <= hitbox.y_bottom))
    puts x_coord
    puts y_coord
    puts hit_status
    render json: hit_status
  end

  private
  def set_world
    @world = World.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/highscore_helper.rb
module HighscoreHelper
end

app/helpers/world_helper.rb
module WorldHelper
end

app/views/highscore/_form.html.erb
<div class="modal-content">
  <h4>You completed the level in <span id="time_placeholder"></span> seconds</h4>
  <h4>Enter your name:</h4>
  <%= form_for [@world, @world.highscores.new]  do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: "Guest", value: "Guest" %>
    <%= hidden_field :highscore, :time, :id => "hidden_time_input", :value => params[:time] %>
     <div class="modal-footer">
      <%= f.submit "Submit", class: " modal-action modal-close waves-effect waves-green btn-flat " %>
    </div>
  <% end %>
</div>

app/views/highscore/index.html.erb
<h1><%= @world.title %> Highscores</h1>
<h4><%= link_to "Play again?", world_url(@world) %></h4>
<div class="divider"></div>
<table>
  <thead>
    <tr>
        <th data-field="rank">Rank</th>
        <th data-field="name">Name</th>
        <th data-field="time">Time (seconds)</th>
    </tr>
  </thead>
  <tbody>
    <% @highscores.each_with_index do |s, i| %>
      <tr>
        <td><%= (i+1) %></td>
        <td><%= s.name %></td>
        <td><%= s.time %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/highscore/new.html.erb
<%= form_tag({controller: "highscore", action: "create", remote: true}, method: "post") do %>
  <%= label_tag("highscore[name]", "Name") %>
  <%= text_field_tag "highscore[name]" %>

  <%= hidden_field :highscore, :time, :value => params[:time] %>
  <%= hidden_field :highscore, :world_id, :value => params[:world_id] %>
  <%= submit_tag "Submit" %>
<% end %>

<%= debug params %> 

app/views/layouts/_character_select.html.erb
<div class="character_select">
  <div class="collection with-header">
    <div class="collection-header"><p><b>Who did you find?</b></p></div>
    <a href="#" class="collection-item avatar select_link" id="waldo_select" data-remote="true" data-character="Waldo">
      <%= image_tag "waldo_char_torso.jpg", class: "circle", alt: "waldo" %> 
      <span class="title">Waldo</span>
    </a>
    <a href="#" class="collection-item avatar select_link" id="whitebeard_select" data-remote="true" data-character="Whitebeard">
      <%= image_tag "whitebeard_char_torso.jpg", class: "circle", alt: "whitebeard" %> 
      <span class="title">Whitebeard</span>
    </a>
    <a href="#" class="collection-item avatar select_link" id="odlaw_select" data-remote="true" data-character="Odlaw">
      <%= image_tag "odlaw_char_torso.jpg", class: "circle", alt: "odlaw" %> 
      <span class="title">Odlaw</span>
    </a>
    <a href="#" class="collection-item avatar select_link" id="wenda_select" data-remote="true" data-character="Wenda">
      <%= image_tag "wenda_char_torso.jpg", class: "circle", alt: "wenda" %> 
      <span class="title">Wenda</span>
    </a>
    <a href="#" class="collection-item" id="nevermind" data-remote="true">
      <span class="title">Nevermind...</span>
    </a>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav>
  <div class="nav-wrapper">
    <%= link_to "Where's Waldo?!", root_url, { class: "brand-logo", id: "logo-link"} %>
    <div class="col s12 right hide-on-med-and-down" id="breadcrumb_menu">
      <%= link_to "Worlds", root_url, { class: "breadcrumb" } %>
      <% if !@world.nil? %>
        <%= link_to @world.title, world_url(@world), { class: "breadcrumb" } %>
      <% end %>
      <% if !@highscores.nil? %>
        <%= link_to "Highscores", world_highscore_index_path(world_id: @world.id), { class: "breadcrumb" } %>
      <% end %>
    </div>
  </div>
</nav>
        

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Waldo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--Import Google Icon Font-->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-74886913-2', 'auto');
    ga('send', 'pageview');

  </script>
</head>
<body class="<%= controller_name %> <%= action_name %>">
  <%= render 'layouts/navbar' %>
  <div class="container">
    <div class="col s12">
      
    </div>
    <div class="divider"></div>
    <%= yield %>
  </div>
</body>
</html>

app/views/world/index.html.erb
<div class="row"> 
  <% @worlds.each do |w| %>
    <div class="col s12 m6 l4">
      <h4><%= w.title %></h4>
      <h6><em><%= w.difficulty %></em></h6>
      <div class="t_image_holder"><%= link_to (image_tag w.image.url(:thumb)), world_path(w) %></div>
    </div>
  <% end %>
</div>

app/views/world/show.html.erb
<div class="row">
  <div class="col l6">
    <h1><%= @world.title %></h1>
    <h5>Difficulty: <%= @world.difficulty %></h5>
  </div>
  <div class="col l6">
    <h5>Time:</h5>
    <h2 id="waldo_timer">0</h2>
    <p>Characters to find: <% @characters.each do |c| %><%= c %> <% end %></p>
  </div>
  <div class="col l12">
    <p><em>Tip: To zoom in, use 'ctrl +' on windows or 'cmd +' on mac. To zoom out, use 'ctrl -' on windows or 'cmd -' on mac.</em></p>
  </div>
</div>
<div class="progress">
  <div class="indeterminate"></div>
</div>
<div class="divider"></div>
<div class="row">
  <div class="col l12">
    <div class='t_large_image_holder'>
      <%= render 'layouts/character_select' %>
      <%= image_tag @world.image.url, class: "world_image" %>
    </div>
  </div>
</div>

<div id="modal1" class="modal">
  <%= render 'highscore/form', world: @world %>
</div>